{{- if .Values.managementService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omada-controller.fullname" . }}-management
  {{- with .Values.managementService.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "omada-controller.labels" . | nindent 4 }}
    {{- with .Values.managementService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.managementService.type }}
  {{- if .Values.managementService.loadBalancerClass }}
  loadBalancerClass: {{ .Values.managementService.loadBalancerClass }}
  {{- end }}
  ports:
  - name: manage-https
    port: {{ .Values.config.ports.manageHttps }}
    targetPort: manage-https
  - name: manage-http
    port: {{ .Values.config.ports.manageHttp }}
    targetPort: manage-http
  selector:
    {{- include "omada-controller.selectorLabels" . | nindent 4 }}
{{- end }}
